name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: |
        npm ci
      continue-on-error: true

    - name: Debug npm
      run: |
        npm list
        cat package.json
        npm version

    - name: Build
      run: npm run build

    - name: Export
      run: npm run export

    - name: Touch .nojekyll
      run: touch out/.nojekyll

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: out